spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 51464557088-qjumn7h4vfv51h7nd0klpvtvqvp2ll3q.apps.googleusercontent.com
            clientSecret: <<Get client secret from https://console.cloud.google.com/>>
server:
  port: 8080